/*
 FAT v0.6.1
 Copyright 2019 Nextapps GmbH
 Author: Thomas Wilkerling
 Released under the Apache 2.0 Licence
 https://github.com/nextapps-de/fat
*/
'use strict';(function(k,f,m){var l;(l=m.define)&&l.amd?l([],function(){return f}):(l=m.modules)?l[k.toLowerCase()]=f:"object"===typeof exports?module.exports=f:m[k]=f})("Fat",function(){function k(a,e,d,c,b,g,B,f,t,v,w,p){this.o=a;this.A=a.j;this.style=e;this.F=e.replace(/([A-Z])/g,"-$1").toLowerCase();this.a=c;this.b=b;this.g=c;this.G=g;this.m=B;this.duration=f;this.f=t;this.ease=l(t)?[]:null;this.start=0;this.i=v;this.h=w;this.D=d;this.c=p;this.C="px"!==g}function f(){this.id=++C;this.stack=[];
this.s=m.bind(this);this.exec=0}function m(a){var e=this.stack.length;if(e){this.exec=requestAnimationFrame(this.s);for(var d=!1,c=0;c<e;c++){var b=this.stack[c];b&&(d=!0,b.B(a)||(this.stack[c]=null))}x=a;d||this.destroy()}}function l(a){return"string"===typeof a}var y=Math.max(screen.width,screen.height),q=parseFloat,C=0,x=0,u=k.prototype;u.animate=function(a){var e=this.a===this.b||!1,d=this.o;a=Math.max(a-(this.start||(this.start=a)),0);var c=a>=this.duration;if(!e)if(c)var b=this.b;else this.ease?
b=this.ease.length?(this.b-this.a)*this.ease[y/this.duration*a+.5>>0]/1E4:(this.b-this.a)*a/this.duration:b=1===this.f.length?this.f(a/this.duration):this.f(a,this.a,this.b,this.duration),b=this.a+b,b=this.C?(b*y+.5>>0)/y:b+.5>>0;var g=this.style;e||this.g===b||(this.g=b,b+=this.G,"custom"!==g&&this.w(b));this.h&&this.h.call(d,c?1:a/this.duration,b);c&&(this.start=-1,this.i&&this.i.call(d))};u.B=function(a){if(-1===this.start)this.o[this.D]=null;else{var e=a-x;if(this.c){if(0<(this.c-=e))return!0;
this.c=0}this.animate(a);return!0}};u.w=function(a){this.A.setProperty(this.F,a,this.m?"important":void 0)};var r=f.prototype;r.v=function(a,e,d,c,b,g,f,z,t,v,w,p){if("custom"===e)c=c||0;else{var n=a.j||(a.j=a.style);c=(c="undefined"===typeof c?n[e]:c)?c:(a.l||(a.l=getComputedStyle(a)))[e]}n=""+c;"auto"===n&&(n="0");c=q(n);if(l(b)){var h=b;b=q(b);g||(g=h.substring((""+b).length))}g||(g=n.substring((""+c).length)||"");e=new k(a,e,d,c,b,g,f,z,t,v,w,p,!1,!1);this.stack[this.stack.length]=e;a[d]=e};r.animate=
function(a,e,d,c){if(a&&e){d?"function"===typeof d&&(c=d,d={}):d={};l(a)?a=document.querySelectorAll(a):a.length||(a=[a]);var b=d.delay||0,g=d.duration||400,f=d.ease||"",z=Object.keys(e),t=z.length;c=c||d.callback||!1;var v=d.step||0,w=d.force||0;d=d.init;for(var p=0;p<t;p++){var n=z[p],h=e[n],k=void 0,m=void 0,q=p===t-1,u="_fat_"+n+this.id;"object"===typeof h&&(b=h.delay||b,g=h.duration||g,f=h.ease||f,k=h.from,m=h.unit,h=h.to);for(var r=0,y=a.length;r<y;r++){var A=a[r];d&&0===p&&(A.l=null);var x=
!d&&A[u];x?x.u(k,h,w,g,f,q&&c,q&&v,b):this.v(A,n,u,k,h,m,w,g,f,q&&c,q&&v,b)}}this.exec||(this.exec=requestAnimationFrame(this.s))}return this};r.destroy=function(){this.exec&&(this.exec=0,this.stack=[]);return this};r.create=function(){return new f};u.u=function(a,e,d,c,b,f,k,m){"undefined"===typeof a?a=this.g:a=q(a);l(e)&&(e=q(e));this.a=a;this.b=e;this.duration=c;this.start=0;this.m=d;this.f!==b&&(this.ease=l(b)?[]:null,this.f=b);this.i=f;this.h=k;this.c=m};return new f}(),this);
