/*
 FAT v0.3.3
 Copyright 2019 Nextapps GmbH
 Author: Thomas Wilkerling
 Released under the Apache 2.0 Licence
 https://github.com/nextapps-de/fat
*/
'use strict';(function(r,g,l){var h;(h=l.define)&&h.amd?h([],function(){return g}):(h=l.modules)?h[r.toLowerCase()]=g:"object"===typeof exports?module.exports=g:l[r]=g})("Fat",function(){function r(a,b,c,d,f,e,g,A,p,B,h,t,n){this.j=a;this.D=a.m;this.style=b;this.a=d;this.b=f;this.g=d;this.v=e;this.s=g;this.duration=A;this.f=p;this.ease=l(p);this.start=0;this.i=B;this.h=h;this.A=c;this.u=t;this.c=n;this.F="px"!==e}function g(){this.id=++K;this.stack=[];this.w=h.bind(this);this.exec=0;this.l=!1}function l(a){if(C(a))if(a){var b;
if(!(b=F[a])){if(b=G[a]||!1){for(var c=new (Int16Array||Array)(x),d=0;d<x;d++)c[d]=1E4*b(d/x)+.5>>0;b=c}else b=[];b=F[a]=b}a=b}else a=[];else a=null;return a}function h(a){var b=this.stack.length;if(b){this.exec=requestAnimationFrame(this.w);E&&(u?u===this.id&&(v={}):(v={},u=this.id));for(var c=!1,d=0;d<b;d++){var f=this.stack[d];f&&(f.B(a)?c=!0:this.stack[d]=null)}H=a;c||this.destroy()}}function C(a){return"string"===typeof a}function z(a){return"undefined"===typeof a}function I(a,b,c){b=w(b);"+"===
c?b=a+b:"-"===c?b=a-b:"*"===c?b*=a:"/"===c&&(b=a/b);return b}var x=Math.max(screen.width,screen.height),J=x,F={},G={},v,w=parseFloat,u,K=0,E=0,H=0,y=r.prototype;y.animate=function(a){var b=this.u,c=this.a===this.b||b&&v[b],d=this.j,f=Math.max(a-(this.start||(this.start=a)),0);a=f>=this.duration;if(!c)if(b&&(v[b]=1),a)var e=this.b;else this.ease?e=this.ease.length?(this.b-this.a)*this.ease[x/this.duration*f+.5>>0]/1E4:(this.b-this.a)*f/this.duration:e=1===this.f.length?this.f(f/this.duration):this.f(f,
this.a,this.b,this.duration),e=this.a+e,e=this.F?(e*J+.5>>0)/J:e+.5>>0;b=this.style;c||this.g===e||(this.g=e,this.C(b,e),this.h&&this.h.call(d,e));a&&(this.start=-1,this.i&&this.i.call(d))};y.B=function(a){if(-1===this.start)this.u||(this.j[this.A]=null);else{var b=a-H;if(this.c){if(0<(this.c-=b))return!0;this.c=0}this.animate(a);return!0}};y.C=function(a,b){"scrollTop"===a?this.j.scrollTop=b:this.D.setProperty(a,b+this.v,this.s?"important":void 0)};var m=g.prototype;m.handle=function(a,b,c,d,f,e,
g,h,p,B,l,t,n,m){var k=a[c];if(k&&!t)k.G(d,f,e,g,h,p,B,l,n);else{"scrollTop"===b?d=z(d)?a.scrollTop:d:(k=a.m||(a.m=a.style),d=(d=z(d)?k[b]:d)?d:(a.o||(a.o=getComputedStyle(a)))[b]);k=""+d;"auto"===k&&(k="0");d=w(k);if(C(f)){var A=f;f="="===f[1]?I(d,A=f.substring(2),f[0]):w(f);e||(e=A.substring((""+f).length))}e||(e=k.substring((""+d).length)||"");b=new r(a,b,c,d,f,e,g,h,p,B,l,t,n,m);this.stack[this.stack.length]=b;t||(a[c]=b)}};m.animate=function(a,b,c){if(a&&b){c||(c={});C(a)?a=document.querySelectorAll(a):
a.length||(a=[a]);var d=c.callback||!1,f=c.step||0,e=c.force||0,g=c.strict||0,h=this.l||c.init,p=c.delay||0,l=c.duration||400;c=c.ease||"";for(var m=Object.keys(b),t=m.length,n=0;n<t;n++){var r=n===t-1,k=m[n],x="_fat_"+k+this.id,q=b[k],u=void 0,w=void 0;"object"===typeof q&&(p=q.delay||p,l=q.duration||l,c=q.ease||c,u=q.from,q=q.to,w=q.unit);for(var v=0,y=a.length;v<y;v++){var D=a[v],z=g&&k+(D._id||(D._id=E++));h&&0===n&&(D.o=null);this.handle(D,k,x,u,q,w,e,l,c,r&&d,r&&f,z,p,!1)}}h&&(this.l=!1);this.exec||
(this.exec=requestAnimationFrame(this.w))}return this};m.destroy=function(){this.exec&&(this.exec=0,this.stack=[],E&&u===this.id&&(u=0));return this};m.init=function(){this.l=!0;return this};m.ease=G;m.create=function(){return new g};y.G=function(a,b,c,d,f,e,g,h,m){z(a)?a=this.g:a=w(a);C(b)&&(b="="===b[1]?I(a,b.substring(2),b[0]):w(b));this.a=a;this.b=b;this.duration=f;this.start=0;this.s=d;this.f!==e&&(this.ease=l(e),this.f=e);this.i=g;this.h=h;this.c=m;c&&(this.v=c)};return new g}(),this);
