/*
 FAT v0.6.1
 Copyright 2019 Nextapps GmbH
 Author: Thomas Wilkerling
 Released under the Apache 2.0 Licence
 https://github.com/nextapps-de/fat
*/
'use strict';(function(x,G,r){var n;(n=r.define)&&n.amd?n([],function(){return G}):(n=r.modules)?n[x.toLowerCase()]=G:"object"===typeof exports?module.exports=G:r[x]=G})("Fat",function(){function x(a,b,c,d,e,f,g,h,C,N,Y,m,l,n,y,u,k,t){this.b=a;this.o=a.w;this.style=b;this.G=b.replace(/([A-Z])/g,"-$1").toLowerCase();this.a=d;this.c=e;this.j=d;this.v=f;this.h=g;this.duration=h;this.g=C;this.ease=P(C);this.start=0;this.m=N;this.l=Y;this.F=c;this.f=m;this.D=k?"%"===f||-1!==b.indexOf("A"):"px"!==f;k&&
(this.i=k,this.u=t);y&&(this.transform=y)}function G(a,b,c){var d=c||-1,e;if("#"===a[0])if(a=a.toLowerCase(),4===a.length){c=q[(e=a[1])+e];var f=q[(e=a[2])+e];var g=q[(e=a[3])+e]}else c=q[a[1]+a[2]],f=q[a[3]+a[4]],g=q[a[5]+a[6]];else e=K(a,"(",")").split(","),c=parseInt(e[0],10),f=parseInt(e[1],10),g=parseInt(e[2],10),3<e.length&&(d=w(e[3])),-1!==a.indexOf("hsl")&&(0===f?f=g=a=g:(a=.5>g?g*(1+f):g+f-g*f,e=2*g-a,f=r(e,a,c+1/3),g=r(e,a,c),a=r(e,a,c-1/3)),c=255*f+.5>>0,f=255*g+.5>>0,g=255*a+.5>>0);a=
{};a[b+"R"]=c;a[b+"G"]=f;a[b+"B"]=g;-1!==d&&(a[b+"A"]=d);return a}function r(a,b,c){0>c?c+=1:1<c&&--c;return c<1/6?a+6*(b-a)*c:.5>c?b:c<2/3?a+(b-a)*(2/3-c)*6:a}function n(){this.id=++Z;this.stack=[];this.C=aa.bind(this);this.exec=0}function P(a){if(L(a))if(a){var b;if(!(b=Q[a])){if(b=M[a]||(M[a]=O.apply(O,ba[a]))){for(var c=new (Int16Array||Array)(v),d=0;d<v;d++)c[d]=1E4*b(d/v)+.5>>0;b=c}else b=[];b=Q[a]=b}a=b}else a=[];else a=null;return a}function aa(a){var b=this.stack.length;if(b){this.exec=requestAnimationFrame(this.C);
for(var c=!1,d=0;d<b;d++){var e=this.stack[d];e&&(c=!0,e.K(a)||(this.stack[d]=null))}R=a;c||this.destroy()}}function L(a){return"string"===typeof a}function D(a){return"undefined"===typeof a}function S(a,b,c){b=w(b);"+"===c?b=a+b:"-"===c?b=a-b:"*"===c?b*=a:"/"===c?b=a/b:"!"===c&&(b=a===b?0:b);return b}function I(a,b,c){if("scrollTop"===b||"scrollLeft"===b)return D(c)?a[b]:c;if("custom"===b)return c||0;var d=a.w||(a.w=a.style);return(c=D(c)?d[b]:c)?c:(a.A||(a.A=getComputedStyle(a)))[b]}function T(a,
b,c,d){if("none"===b)return b=a.substring(0,a.length-1),c[a]="scale"===b?1:0,d&&(d[d.length]=b),c;-1!==b.indexOf("matrix")&&(b=K(b,"(",")").split(","),b=a+"("+(parseFloat(b[ca[a]])||"")+")");a=b.replace(/, /g,",").split(" ");b={};for(var e=0,f=0;f<a.length;f++){var g=a[f],h=K(g,"(");if(h){g=K(g,"(",")").split(",");var C=g.length;2<C&&(h=h.replace("3d",""),c[h+"Z"]=g[2]);1<C?(c[h+"X"]=g[0],c[h+"Y"]=g[1]):(c[h]=g[0],h=h.substring(0,h.length-1));b[h]||(d&&(d[e++]=h),b[h]=1)}}return c}function da(a,b,
c){var d=a.s;if(d)var e=a.B;else a.s=d={},a.B=e=[];if(!d||D(d[b]))a=c||I(a,U||"transform"),T(b,a,d,e);return d[b]}function ea(a,b,c,d){var e="_"+d,f=a[e];f||(c=c||I(a,d),a[e]=f=G(c,d,1));return f[b]}function K(a,b,c){var d=a.indexOf(b);return-1!==d?c?a.substring(d+b.length,a.indexOf(c)):a.substring(0,d):""}function V(a,b,c){if(a&&b){c?"function"===typeof c&&(c={callback:c}):c={};L(a)?a=document.querySelectorAll(a):a.length||(a=[a]);var d=c.delay||0,e=c.duration||400,f=c.ease;if(f){var g;if(L(f)){if(g=
K(f,"bezier(",")")){g=g.replace(/ /g,"");var h=g.split(",")}}else f.constructor===Array&&(g=f.join(","),h=f);g&&(M[g]||(M[g]=O.apply(O,h)),f=g)}g=f||"";h=Object.keys(b);f=h.length;var C=c.callback||!1,N=c.step||0,m=c.force||0;c=c.init;for(var l,n,r,y,u=f;0<u--;){var k=h[u];if("transform"===k){l=T(k,b[k],{});k=Object.keys(l);for(var t=0;t<k.length;t++){var p=k[t];h.push(p);b[p]=l[p];f++}l=k[k.length-1]}else if(!l&&W[k])l=k;else if(t=X[k]){if(0>t){p=b[k];"object"===typeof p&&(p=p.to);var z=G(p,k);h.push(p=
k+"R");b[p]=z[p];h.push(p=k+"G");b[p]=z[p];h.push(p=k+"B");b[p]=z[p];var E=!D(z=z[p=k+"A"]);E?(h.push(p),b[p]=z,k=p):k+="B";f+=E?4:3;t*=-1}n||1!==t?r||2!==t?y||3!==t||(y=k):r=k:n=k}}for(u=0;u<f;u++){E=z=p=t=void 0;var q=h[u],A=b[q],w=void 0,v=void 0,x=u===f-1,F="_fat_"+q+this.id;"object"===typeof A&&(d=A.delay||d,e=A.duration||e,g=A.ease||g,w=A.from,v=A.unit,A=A.to);if("transform"!==q){k=W[q]&&l;var B=X[q];if(B){if(0>B)continue;1===B?(t=n,E="color"):2===B?(p=r,E="backgroundColor"):3===B&&(z=y,E="borderColor")}B=
0;for(var J=a.length;B<J;B++){var H=a[B];c&&0===u&&(H.A=null,l?H.s=null:n?H.P=null:r?H.N=null:y&&(H.O=null));var I=!c&&H[F];I?I.I(w,A,m,e,g,x&&C,x&&N,d,k,t||p||z,E):this.J(H,q,F,w,A,v,m,e,g,x&&C,x&&N,d,k,t||p||z,E)}}}this.exec||(this.exec=requestAnimationFrame(this.C))}return this}var v=Math.max(screen.width,screen.height),Q={},M={},l=function(){var a=getComputedStyle(document.body);if(D(a.transform))for(var b=["webkit","moz","ms","o"],c=0,d;c<b.length;c++){if(!D(a[(d=b[c])+"Transform"]))return d}else return""}(),
U=l&&l+"Transform",fa=l&&"-"+U.replace(/([A-Z])/g,"-$1").toLowerCase(),w=parseFloat,Z=0,R=0,ba={easeIn:[.55,.085,.68,.53],easeOut:[.25,.46,.45,.94],easeInOut:[.455,.03,.515,.955],cubicIn:[.55,.055,.675,.19],cubicOut:[.215,.61,.355,1],cubicInOut:[.645,.045,.355,1],quartIn:[.895,.03,.685,.22],quartOut:[.165,.84,.44,1],quartInOut:[.77,0,.175,1],quintIn:[.755,.05,.855,.06],quintOut:[.23,1,.32,1],quintInOut:[.86,0,.07,1],expoIn:[.95,.05,.795,.035],expoOut:[.19,1,.22,1],expoInOut:[1,0,0,1],circIn:[.6,.04,
.98,.335],circOut:[.075,.82,.165,1],circInOut:[.785,.135,.15,.86],sineIn:[.47,0,.745,.715],sineOut:[.39,.575,.565,1],sineInOut:[.445,.05,.55,.95],backIn:[.6,-.28,.735,.045],backOut:[.175,.885,.32,1.275],backInOut:[.68,-.55,.265,1.55],snap:[.1,1,.1,1]},O=function(){function a(a,c,d,e){this.a=a;this.i=c;this.b=d;this.j=e}a.prototype.c=function(a,c){return 1-3*c+3*a};a.prototype.f=function(a,c){return 3*c-6*a};a.prototype.g=function(a){return 3*a};a.prototype.h=function(a,c,d){return((this.c(c,d)*a+
this.f(c,d))*a+this.g(c))*a};a.prototype.l=function(a,c,d){return 3*this.c(c,d)*a*a+2*this.f(c,d)*a+this.g(c)};a.prototype.m=function(a){for(var b=a,d=0;4>d;++d){var e=this.l(b,this.a,this.b);if(0===e)break;b-=(this.h(b,this.a,this.b)-a)/e}return b};a.prototype.o=function(a){return 0===a||1===a||this.a===this.i&&this.b===this.j?a:this.h(this.m(a),this.i,this.j)};return function(b,c,d,e){b=new a(b,c,d,e);return b.o.bind(b)}}();l=x.prototype;l.animate=function(a){var b=this.a===this.c||!1,c=this.b;
a=Math.max(a-(this.start||(this.start=a)),0);var d=a>=this.duration;if(!b)if(d)var e=this.c;else this.ease?e=this.ease.length?(this.c-this.a)*this.ease[v/this.duration*a+.5>>0]/1E4:(this.c-this.a)*a/this.duration:e=1===this.g.length?this.g(a/this.duration):this.g(a,this.a,this.c,this.duration),e=this.a+e,e=this.D?(e*v+.5>>0)/v:e+.5>>0;var f=this.style;b||this.j===e||(this.j=e,this.transform?c.s[f]=e+this.v:this.i?c["_"+this.u][f]=e:(e+=this.v,"custom"!==f&&this.L(f,e)));f===this.transform?e=this.H():
f===this.i&&(e=this.M(this.u));this.l&&this.l.call(c,d?1:a/this.duration,e);d&&(this.start=-1,this.m&&this.m.call(c))};l.K=function(a){if(-1===this.start)this.b[this.F]=null;else{var b=a-R;if(this.f){if(0<(this.f-=b))return!0;this.f=0}this.animate(a);return!0}};l.L=function(a,b){"scrollTop"===a||"scrollLeft"===a?this.b[a]=b:this.o.setProperty(this.G,b,this.h?"important":void 0)};var X=function(a){function b(b,d){a[b]=-d;a[b+"R"]=d;a[b+"G"]=d;a[b+"B"]=d;a[b+"A"]=d}b("color",1);b("backgroundColor",
2);b("borderColor",3);return a}({}),W=function(a){function b(b,d){a[b]=d;a[b+"X"]=d;a[b+"Y"]=d;a[b+"Z"]=d;a[b+"3d"]=d}b("translate",1);b("scale",2);b("rotate",3);b("skew",4);return a}({}),ca={scaleX:0,skewY:1,skewX:2,scaleY:3,translateX:4,translateY:5};var q={};var J=Array(255);for(var m=0;256>m;m++){var F=m.toString(16);F.length%2&&(F="0"+F);q[F]=m;J[m]=F}l.H=function(){for(var a=this.b.s,b=this.o,c=this.b.B,d="",e=0,f=c.length;e<f;e++){var g=c[e],h="scale"===g?1:0,l=a[g+"X"],m=a[g+"Y"],n=a[g+"Z"];
if(l||m||n)"rotate"===g&&(l&&(d+=g+"X("+(l||h)+") "),m&&(d+=g+"Y("+(m||h)+") ")),n&&w(n)!==h?d="rotate"===g?d+(g+"Z("+(n||h)+") "):d+(g+"3d("+(l||h)+","+(m||h)+","+n+") "):"rotate"!==g&&(d+=g+"("+(l||h)+","+(m||h)+") ")}b.setProperty(fa||"transform",d,this.h?"important":void 0);return a};l.M=function(a){var b=this.b["_"+a],c=this.o,d=a.replace("C","-c"),e=b[a+"R"]||0,f=b[a+"G"]||0,g=b[a+"B"]||0;a=b[a+"A"];"%"===this.v&&(e=2.55*e+.5>>0,f=2.55*f+.5>>0,g=2.55*g+.5>>0,a&&(a/=100));c.setProperty(d,1===
a||D(a)?"#"+J[e]+J[f]+J[g]:"rgba("+e+","+f+","+g+","+a+")",this.h?"important":void 0);return b};m=n.prototype;m.J=function(a,b,c,d,e,f,g,h,l,m,n,q,r,v,y){var u=""+(r?da:v?ea:I)(a,b,d,y);"auto"===u&&(u="0");d=w(u);if(L(e)){var k=e;e="="===e[1]?S(d,k=e.substring(2),e[0]):w(e);f||(f=k.substring((""+e).length));"%"===f&&("scrollTop"===b?(e*=(a.scrollHeight-a.clientHeight)/100,f=""):"scrollLeft"===b&&(e*=(a.scrollWidth-a.clientWidth)/100,f=""))}f||(f=u.substring((""+d).length)||"");b=new x(a,b,c,d,e,f,
g,h,l,m,n,q,!1,!1,r,void 0,v,y);this.stack[this.stack.length]=b;a[c]=b};m.animate=V;m.destroy=function(){this.exec&&(this.exec=0,this.stack=[]);return this};m.create=function(){return new n};m.ease=M;m.transform=V;l.I=function(a,b,c,d,e,f,g,h,l,m,n){D(a)?a=this.j:a=w(a);L(b)&&(b="="===b[1]?S(a,b.substring(2),b[0]):w(b));this.a=a;this.c=b;this.duration=d;this.start=0;this.h=c;this.g!==e&&(this.ease=P(e),this.g=e);this.m=f;this.l=g;this.f=h;l&&(this.transform=l);m&&(this.i=m,this.u=n)};return new n}(),
this);
