/*
 FAT v0.4.1
 Copyright 2019 Nextapps GmbH
 Author: Thomas Wilkerling
 Released under the Apache 2.0 Licence
 https://github.com/nextapps-de/fat
*/
'use strict';(function(v,g,k){var h;(h=k.define)&&h.amd?h([],function(){return g}):(h=k.modules)?h[v.toLowerCase()]=g:"object"===typeof exports?module.exports=g:k[v]=g})("Fat",function(){function v(a,b,c,d,f,e,g,K,l,D,h,w,p){this.j=a;this.F=a.m;this.style=b;this.a=d;this.b=f;this.g=d;this.v=e;this.s=g;this.duration=K;this.f=l;this.ease=k(l);this.start=0;this.i=D;this.h=h;this.H=c;this.u=w;this.c=p;this.G="px"!==e}function g(){this.id=++L;this.stack=[];this.w=h.bind(this);this.exec=0;this.l=!1}function k(a){if(C(a))if(a){var b;
if(!(b=F[a])){if(b=G[a]||!1){for(var c=new (Int16Array||Array)(q),d=0;d<q;d++)c[d]=1E4*b(d/q)+.5>>0;b=c}else b=[];b=F[a]=b}a=b}else a=[];else a=null;return a}function h(a){var b=this.stack.length;if(b){this.exec=requestAnimationFrame(this.w);E&&(r?r===this.id&&(z={}):(z={},r=this.id));for(var c=!1,d=0;d<b;d++){var f=this.stack[d];f&&(f.C(a)?c=!0:this.stack[d]=null)}H=a;c||this.destroy()}}function C(a){return"string"===typeof a}function A(a){return"undefined"===typeof a}function I(a,b,c){b=t(b);"+"===
c?b=a+b:"-"===c?b=a-b:"*"===c?b*=a:"/"===c&&(b=a/b);return b}var q=Math.max(screen.width,screen.height),J=q,F={},G={},z,t=parseFloat,r,L=0,E=0,H=0,x=v.prototype;x.animate=function(a){var b=this.u,c=this.a===this.b||b&&z[b],d=this.j,f=Math.max(a-(this.start||(this.start=a)),0);a=f>=this.duration;if(!c)if(b&&(z[b]=1),a)var e=this.b;else this.ease?e=this.ease.length?(this.b-this.a)*this.ease[q/this.duration*f+.5>>0]/1E4:(this.b-this.a)*f/this.duration:e=1===this.f.length?this.f(f/this.duration):this.f(f,
this.a,this.b,this.duration),e=this.a+e,e=this.G?(e*J+.5>>0)/J:e+.5>>0;b=this.style;c||this.g===e||(this.g=e,this.D(b,e));this.h&&this.h.call(d,e);a&&(this.start=-1,this.i&&this.i.call(d))};x.C=function(a){if(-1===this.start)this.u||(this.j[this.H]=null);else{var b=a-H;if(this.c){if(0<(this.c-=b))return!0;this.c=0}this.animate(a);return!0}};x.D=function(a,b){"scrollTop"===a?this.j.scrollTop=b:this.F.setProperty(a,b+this.v,this.s?"important":void 0)};var u=g.prototype;u.B=function(a,b,c,d,f,e,g,h,
l,D,k,w,p){if("scrollTop"===b)d=A(d)?a.scrollTop:d;else{var m=a.m||(a.m=a.style);d=(d=A(d)?m[b]:d)?d:(a.o||(a.o=getComputedStyle(a)))[b]}m=""+d;"auto"===m&&(m="0");d=t(m);if(C(f)){var y=f;f="="===f[1]?I(d,y=f.substring(2),f[0]):t(f);e||(e=y.substring((""+f).length))}e||(e=m.substring((""+d).length)||"");b=new v(a,b,c,d,f,e,g,h,l,D,k,w,p,!1);this.stack[this.stack.length]=b;w||(a[c]=b)};u.animate=function(a,b,c){if(a&&b){c||(c={});C(a)?a=document.querySelectorAll(a):a.length||(a=[a]);var d=c.callback||
!1,f=c.step||0,e=c.force||0,g=c.strict||0,h=this.l||c.init,l=c.delay||0,k=c.duration||400;c=c.ease||"";for(var u=Object.keys(b),w=u.length,p=0;p<w;p++){var m=p===w-1,y=u[p],v="_fat_"+y+this.id,n=b[y],q=void 0,r=void 0;"object"===typeof n&&(l=n.delay||l,k=n.duration||k,c=n.ease||c,q=n.from,n=n.to,r=n.unit);for(var t=0,z=a.length;t<z;t++){var B=a[t],x=g&&y+(B._id||(B._id=E++));h&&0===p&&(B.o=null);var A=B[v];A&&!x?A.A(q,n,r,e,k,c,m&&d,m&&f,l):this.B(B,y,v,q,n,r,e,k,c,m&&d,m&&f,x,l)}}h&&(this.l=!1);
this.exec||(this.exec=requestAnimationFrame(this.w))}return this};u.destroy=function(){this.exec&&(this.exec=0,this.stack=[],E&&r===this.id&&(r=0));return this};u.init=function(){this.l=!0;return this};u.ease=G;u.create=function(){return new g};x.A=function(a,b,c,d,f,e,g,h,l){A(a)?a=this.g:a=t(a);C(b)&&(b="="===b[1]?I(a,b.substring(2),b[0]):t(b));this.a=a;this.b=b;this.duration=f;this.start=0;this.s=d;this.f!==e&&(this.ease=k(e),this.f=e);this.i=g;this.h=h;this.c=l;c&&(this.v=c)};return new g}(),
this);
